on:
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: "1.1.15"
    - name: Install poetry dependencies
      run: poetry install
    #- name: Prefect Cloud login
    #  run: |
    #    poetry run prefect config set PREFECT_API_KEY=${{secrets.PREFECT_API_KEY}} 
    #    poetry run prefect cloud workspace set --workspace "${{secrets.PREFECT_WORKSPACE}}"
    #- name: Run extract web to GCS
    #  run: poetry run python flows/extract_web-to-gcs.py


